### ISSUE TITLE
Modules not importing correctly...

### ISSUE THREAD

**Issue by pushtheworldllc** [OpenBCI/openbci-js-sdk#17]
Several developers have complained that the module is not requiring properly. 
The following do not import in the entry file:
var k = require('./OpenBCIConstants');
var OpenBCISample = require('./OpenBCISample');
var serialPort = require('serialport');

**Comment by pushtheworldllc** [comment]
Found this:
https://discuss.atom.io/t/cant-use-app-module-in-render-process/17326/3
Which leads me to thinking we might have to use this:
https://github.com/atom/electron/blob/master/docs/api/remote.md

Not sure just digging

**Comment by pushtheworldllc** [comment]
Thinking this might be a bug with electron, closing here and opening over on OpenEXP

**Comment by pushtheworldllc** [comment]
So when i use the module in my program, i find the problem to come from v8. The function that throws the error is called `Module._resolveFilename` and it takes two inputs, a `request` and a `parent`.
The problem is that v8 is looking for `"./openBCISample" in paths `"/Users/ajk/Thinker/client" versus in the node_module. 
![screenshot 2016-01-16 09 51 30](https://cloud.githubusercontent.com/assets/11437469/12372953/d329edc2-bc36-11e5-9cd2-fc22a52b7f5b.png)

**Comment by teonlamont** [comment]
I'm sorry but I don't understand what the error is that is related to loading the constants.

**Comment by pushtheworldllc** [comment]
I have three .js files in the project:

* openBCISample
* openBCIConstants
* openBCIBoard

All three are module.exports and all three are at the same level in the same directory.
In `openBCIBoard` I have to `require` at least `openBCISample` so:
```js
var openBCISample = require('./openBCISample');
var k = openBCISample.k;
```

However THIS issue comes from when v8 is trying to load `openbci-sdk` at runtime in say `OpenEXP` and when it get's to the line 
```js
var openBCISample = require('./openBCISample');
```
It throws the error cannot find module `./openBCISample` because there is no file called `./openBCISample` in the main project directory of OpenEXP.

**Comment by teonlamont** [comment]
ah, got it. because it's not properly interpreting local imports

**Comment by pushtheworldllc** [comment]
Yes!!! Need to figure out how to do that!

--------------------------------------------
 
AJ Keller
Founder & CEO
Push The World LLC
Work: (843) 471-0039
Cell: (203) 733-4538

Warning: The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and destroy this material.

**Comment by pushtheworldllc** [comment]
thanks to @tashoecraft we are closing this!
