### ISSUE TITLE
change simulator name for usability

### ISSUE THREAD

**Issue by pushtheworldllc** [OpenBCI/openbci-js-sdk#27]
Change name of simulator from `/dev/tty.OpenBCISimulator` to just `simulator`

**Comment by pushtheworldllc** [comment]
@tashoecraft

**Comment by teonlamont** [comment]
I would maybe keep `OpenBCISimulator`

**Comment by pushtheworldllc** [comment]
Changed to `OpenBCISimulator`

Will be released with next update
