### ISSUE TITLE
Simulate bio-like data

### ISSUE THREAD

**Issue by alexcastillo** [OpenBCI/openbci-js-sdk#44]
Is there a way the simulated data can be more bio-like?

**Comment by pushtheworldllc** [comment]
Record a lot of bio data, store and read from it? I would be cool with using it as long as it is stored in 24-bit signed integers or we convert the floats to 24-bit signed integers.

**Comment by pushtheworldllc** [comment]
The main purpose of the simulator is for CI. So just want to make sure we are covered with the core functions.

**Comment by pushtheworldllc** [comment]
Ok i think we can do this. I've been thinking about it for a couple days and talked with @teonbrooks  yesterday about it too. Seems like if we do a sum of sine waves that decrease in power as the frequency increases we should be able to simulate some brainwaves.

**Comment by alexcastillo** [comment]
I like the idea!

**Comment by teonbrooks** [comment]
we can make sure the time-frequency has the 1/f characteristic. that would help

**Comment by pushtheworldllc** [comment]
from a guy with 15+ years experience confirming teon: "1/f + a little bump around 10 Hz and you have a pretty realistic power spectrum" 

@teonbrooks do you want to do this pr?

**Comment by teonbrooks** [comment]
yeah, I would like to do that.

**Comment by pushtheworldllc** [comment]
This issue is resolved with #56

**Comment by pushtheworldllc** [comment]
Will be in 0.3.4
