### ISSUE TITLE
Simulate auxData

### ISSUE THREAD

**Issue by alexcastillo** [OpenBCI/openbci-js-sdk#61]
It would be great to get simulated auxData. Currently just getting [0, 0, 0].

**Comment by pushtheworldllc** [comment]
Could do one for the accel pretty easy. just every ten packet inject some fake accel data.

**Comment by alexcastillo** [comment]
Yes, that's exactly what I need.

**Comment by pushtheworldllc** [comment]
Added this feature request in #62
